Basic coding guidlines
frenchbakery/dev_template pull request #2
Opened 2023-02-01 14:26 UTC by Nilusink

Implemented a basic overview of how code should be written.

2023-02-01 18:04 UTC, melektron commented on CodeGuidines.md
> +Similarly to **Classes**, Types should be written in **PascalCase** with an added **_T** at the end.
The "_T" needs to be lowercase: "_t". Actually, I think it would be better if the entire type name is lowercase. Use an alias as an example for a type:

```cpp
using my_number_t = double;
```

2023-02-01 18:06 UTC, melektron commented on CodeGuidines.md
> +```
Maybe also add the following sentence:

This also includes structures whose primary use is a simple data container:

```cpp
struct coord_t
{
    int x, y, z;
}
```

2023-02-01 18:08 UTC, melektron commented on CodeGuidines.md
> +Otherwise use a **alllowercase** style.
**snake_case** style, though it is preferred to use short namespace names with only one word.

2023-02-01 18:13 UTC, melektron commented on CodeGuidines.md
> +For every include of files that have been written for **this** project, `""` should be used.
maybe add:

..., even if the path is relative to the src folder and not relative to the file.

```cpp
#include "utils.hpp"
#include "hw/drivers/gripper.hpp"
```

2023-02-01 18:20 UTC, melektron commented on CodeGuidines.md
> +```
Maybe add a section about classes vs structs:

## Classes and Structures

When the primary purpose of an object is to compute complex operations or implement advanced functionality in the form of member functions, **class** should be used:

```cpp
class MyClass
{
    int myfunc1(...);
    int myfunc2(...);
    int myfunc3(...);
    int myfunc4(...);
    .
    .
};
```

When the primary purpose of an object is to store **simple** data grouped as one "type", **struct** should be used:

```cpp
struct vector_t
{
    double x, y, z;
    int len();
};
```

2023-02-01 18:22 UTC, melektron requested changes
Very nice structure and good guidelines. I would suggest adding a few more details and section like I have commented.

2023-02-06 11:17 UTC, LukasKrah requested changes
Please correct typo

2023-02-06 11:17 UTC, LukasKrah commented on CodeGuidines.md
> +If possile Every library for written should be sepperated into a header (`.hpp`) and a implementation file (`.cpp`). **Defenitions** and **Documentation** for the function should be made in the heade
"separated" is written with just one "p"

2023-02-06 16:57 UTC, LukasKrah commented on CodeGuidines.md
> +If possile Every library for written should be sepperated into a header (`.hpp`) and a implementation file (`.cpp`). **Defenitions** and **Documentation** for the function should be made in the heade
And of course please change the start of the sentence to "If possi**b**le **e**very". And the sentence makes no sense

2023-02-21 13:42 UTC, LukasKrah commented
Changes moved to [DevDocs](https://github.com/frenchbakery/devdocs) Repository

2023-02-21 13:42 UTC, closed without merging